/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface_agency;

import Business.Customer;
import Business.Flight;
import Business.Seat;
import Business.Ticket;
import java.awt.CardLayout;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author zhanghaojie
 */
public class ReserveJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReserveJPanel
     */
    private JPanel XJpanel;
    private Flight flight;
    private Map<Integer, Customer> customerMap;
    public ReserveJPanel(JPanel XJpanel, Flight flight, Map<Integer, Customer> customerMap) {
        initComponents();
        this.XJpanel = XJpanel;
        this.flight = flight;
        this.customerMap = customerMap;
        initData();
    }
    
     private void initData() {
        initBox();
        flightTextField.setText(flight.toString());
        dpTextField.setText(flight.getDeparture());
        dtTextField.setText(flight.getArrival());
    }
     
     private void initBox() {
        custComboBox.removeAllItems();
        for (Map.Entry<Integer, Customer> customers : this.customerMap.entrySet()) {
            Customer customer = customers.getValue();
            custComboBox.addItem(String.valueOf(customer));
       
        Seat[][] seats = flight.getSeatTable();

        rowBox.removeAllItems();
        rowBox.addItem("--select--");
        for (Seat seat : getSeatByCol(seats, 0)) {
            if (!seat.isIsAvai()) {
                continue;
            }
            rowBox.addItem(String.valueOf(seat));
        }

        lineBox.removeAllItems();
        lineBox.addItem("--select--");
        for (Seat seat : getSeatByCol(seats, 1)) {
            if (!seat.isIsAvai()) {
                continue;
            }
            lineBox.addItem(String.valueOf(seat));
        }          
      
     }
  }
     
       private Seat[] getSeatByCol(Seat[][] seats, int col) {
        Seat[] colSeat = new Seat[seats.length];
        for (int i = 0; i < seats.length; i++) {
            for (int j = 0; j < seats[0].length; j++) {
                if (j == col) {
                    colSeat[i] = seats[i][j];
                }
            }
        }
        return colSeat;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        flightTextField = new javax.swing.JTextField();
        dpTextField = new javax.swing.JTextField();
        dtTextField = new javax.swing.JTextField();
        custComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        rowBox = new javax.swing.JComboBox<>();
        lineBox = new javax.swing.JComboBox<>();
        backjButton = new javax.swing.JButton();
        reservejButton = new javax.swing.JButton();

        jLabel1.setText("Flight");

        jLabel2.setText("Departure");

        jLabel3.setText("Destination");

        jLabel4.setText("Customer");

        jLabel5.setText("Seat Choice :");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--select--", "First Class ", "Business Class ", "Economy Class " }));

        rowBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--select--", "Row 1", "Row 2", "Row 3", "Row 4", "Row 5 " }));

        lineBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--select--", "01", "02", "03", "05", "06", " " }));

        backjButton.setText("<Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        reservejButton.setText("Reserve");
        reservejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservejButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(47, 47, 47)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(84, 84, 84)
                                    .addComponent(rowBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lineBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                    .addGap(52, 52, 52)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(flightTextField)
                                        .addComponent(dpTextField)
                                        .addComponent(dtTextField)
                                        .addComponent(custComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reservejButton)
                            .addComponent(backjButton))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(backjButton)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(custComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rowBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lineBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(reservejButton)
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
      XJpanel.remove(this);
      CardLayout cLayout = (CardLayout) XJpanel.getLayout();
      cLayout.previous(XJpanel);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void reservejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservejButtonActionPerformed
     Object customer = custComboBox.getSelectedItem();
        if (!(customer instanceof Customer)) {
            JOptionPane.showMessageDialog(this, "Please select at least a customer.", "INFORMATION", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Customer c = (Customer) customer;

        Object owlSeat = rowBox.getSelectedItem();
        Seat wlSeat;
        Object owrSeat = lineBox.getSelectedItem();
        Seat wrSeat;
        

        if ((!(owlSeat instanceof Seat)) && (!(owrSeat instanceof Seat))) {
            JOptionPane.showMessageDialog(this, "Please select at least a seat.", "INFORMATION", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Map<Integer, Ticket> ticketMap = c.getTicketMap();
                
        if (owlSeat instanceof Seat) {
            wlSeat = (Seat) owlSeat;
            wlSeat.setIsAvai(false);
            Ticket ticket = new Ticket(wlSeat, flight.getDeparture(), flight.getArrival());
            ticketMap.put(ticket.getTicketID(), ticket);
        }
        if (owrSeat instanceof Seat) {
            wrSeat = (Seat) owrSeat;
            wrSeat.setIsAvai(false);
            Ticket ticket = new Ticket(wrSeat, flight.getDeparture(), flight.getArrival());
            ticketMap.put(ticket.getTicketID(), ticket);
       
        
        
        initBox();
        JOptionPane.showMessageDialog(this, "Reserve Ok", "CREATE", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_reservejButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JComboBox<String> custComboBox;
    private javax.swing.JTextField dpTextField;
    private javax.swing.JTextField dtTextField;
    private javax.swing.JTextField flightTextField;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> lineBox;
    private javax.swing.JButton reservejButton;
    private javax.swing.JComboBox<String> rowBox;
    // End of variables declaration//GEN-END:variables
}
