/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import Business.WorkQueue.WorkQueue;
import Business.WorkQueue.WorkRequest;
import Business.WorkQueue.commentrequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author junyaoli
 */
public class RequestorderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestorderJPanel
     */
    private commentrequest request;
    private ArrayList menue;
    private ArrayList orderList;
    private UserAccount account;
    private JPanel userProcessContainer;
    private EcoSystem system;
    
    public RequestorderJPanel(JPanel userProcessContainer, UserAccount account,EcoSystem system) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.system=system;
        this.request = new commentrequest();
        this.menue = request.getOrder();
        
//        this.orderList=account.getWorkQueue().getWorkRequestList();
        populateRequestTable();
    }
     public void populateRequestTable(){

            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);         
            if (menue != null){
                  for(Object d : menue){
                    Object[] row = new Object[2];
                    row[0]=d;
                    row[1]=1;
                    dtm.addRow(row);
                }
            }
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addTestJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        messageJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        orderTestJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        RestaurantJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        messageJTextField3 = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addTestJButton.setText("add");
        addTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTestJButtonActionPerformed(evt);
            }
        });
        add(addTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        jLabel1.setText("Dish");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, 10));
        add(messageJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 89, 20));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 28, 130, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Order:");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 18, 120, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Dish", "Number"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 54, 200, 145));

        orderTestJButton.setText("order");
        orderTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderTestJButtonActionPerformed(evt);
            }
        });
        add(orderTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        jLabel2.setText("Dish");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, 10));
        add(RestaurantJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 89, -1));

        jLabel4.setText("Restaurant");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 20));
        add(messageJTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 89, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTestJButtonActionPerformed
        menue.add(messageJTextField.getText());
        populateRequestTable();
    }//GEN-LAST:event_addTestJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CustomerAreaJPanel dwjp = (CustomerAreaJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backJButtonActionPerformed

    private void orderTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderTestJButtonActionPerformed
        // TODO add your handling code here:
   
        String res= RestaurantJTextField.getText();
//      查找指定餐厅
        UserAccount restaurant =  system.getUseraccountdirectory().findUser(res);
        if (restaurant!=null) {
        request.setReceiver(restaurant);     
        request.setOrder(this.menue);
        request.setStatus("pending");
//       加入指定餐厅的工作行程中
        restaurant.getWorkQueue().getWorkRequestList().add(request);
        }
       

    }//GEN-LAST:event_orderTestJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField RestaurantJTextField;
    private javax.swing.JButton addTestJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField messageJTextField;
    private javax.swing.JTextField messageJTextField3;
    private javax.swing.JButton orderTestJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
