

package userinterface.RestaurantAdminRole;


import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import com.sun.jmx.snmp.UserAcl;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.SystemAdminWorkArea.ManageRestaureantJPanel;

/**
 *
 * @author  raunak
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount account;
    
    /** Creates new form AdminWorkAreaJPanel */
    public AdminWorkAreaJPanel(JPanel userProcessContainer, EcoSystem system, UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system=system;
        this.account=account;
        
        //valueLabel.setText();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageRestaurantJButton = new javax.swing.JButton();
        managemenueJButton = new javax.swing.JButton();
        manageOrderJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area -Adminstrative Role");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        manageRestaurantJButton.setText("Manage Restaurant Info");
        manageRestaurantJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageRestaurantJButtonActionPerformed(evt);
            }
        });
        add(manageRestaurantJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 180, -1));

        managemenueJButton.setText("Manage menue");
        managemenueJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managemenueJButtonActionPerformed(evt);
            }
        });
        add(managemenueJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 150, -1));

        manageOrderJButton.setText("Manage Orders");
        manageOrderJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrderJButtonActionPerformed(evt);
            }
        });
        add(manageOrderJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Restaurant :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 120, 30));

        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void manageRestaurantJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageRestaurantJButtonActionPerformed
        // TODO add your handling code here: 
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add(new RestaurantinformationJPanel(userProcessContainer,  system,  account));
            layout.next(userProcessContainer); 
        
    }//GEN-LAST:event_manageRestaurantJButtonActionPerformed

    private void managemenueJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managemenueJButtonActionPerformed
             CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add(new ManagemenueJPanel(userProcessContainer,  system,  account));
            layout.next(userProcessContainer); 
    }//GEN-LAST:event_managemenueJButtonActionPerformed

    private void manageOrderJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrderJButtonActionPerformed
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add(new ManageOrderJPanel ( userProcessContainer,  system,  account));
            layout.next(userProcessContainer); 
    }//GEN-LAST:event_manageOrderJButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageOrderJButton;
    private javax.swing.JButton manageRestaurantJButton;
    private javax.swing.JButton managemenueJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
    
}
