/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.DeliveryMan.DeliveryMan;
import Business.DeliveryMan.DeliveryManDirectory;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Role.DeliverManRole;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.commentrequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author junyaoli
 */
public class ManageDelivermanJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount account;
    /**
     * Creates new form ManageDelivermanJPanel
     */
    public ManageDelivermanJPanel(JPanel userProcessContainer, EcoSystem system, UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system=system;
        this.account=account;
    }
public void populateRequestTable(){

            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);      
            ArrayList<DeliveryMan> worklist= system.getDeliveryManDirectory().getDeliveryManDirectory();
            
            if (worklist != null){  
                for(DeliveryMan request : worklist){
                    Object[] row = new Object[2];
                    row[0]=request.getId();
                    row[1]=request.getName();     
                    dtm.addRow(row);
                }
            }
          
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        createusernamejTextField1 = new javax.swing.JTextField();
        createpasswordjTextField1 = new javax.swing.JTextField();
        selectjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        createjButton = new javax.swing.JButton();
        deletejButton = new javax.swing.JButton();
        modifyjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        usernamejTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        passwordjTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("User name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, -1));

        jLabel3.setText("Password");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));
        add(createusernamejTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 100, -1));
        add(createpasswordjTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 100, -1));

        selectjButton.setText("Select");
        selectjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectjButtonActionPerformed(evt);
            }
        });
        add(selectjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 244, 184));

        createjButton.setText("Create");
        createjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createjButtonActionPerformed(evt);
            }
        });
        add(createjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, -1));

        deletejButton.setText("Delete");
        deletejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletejButtonActionPerformed(evt);
            }
        });
        add(deletejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, -1, -1));

        modifyjButton.setText("Modify");
        modifyjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyjButtonActionPerformed(evt);
            }
        });
        add(modifyjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, -1));

        jLabel1.setText("Deliverman List");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));
        add(usernamejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 100, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        add(passwordjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 100, -1));

        jLabel4.setText("User name");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, 30));

        jLabel5.setText("Password");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void selectjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectjButtonActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null,"Please select a row!", "get Request",JOptionPane.ERROR_MESSAGE);
        } 
        String name = jTable1.getValueAt(row,0).toString();
        UserAccount del = system.getUseraccountdirectory().findUser(name);
        
        usernamejTextField.setText(del.getUsername());
        passwordjTextField.setText(del.getPassword());
    }//GEN-LAST:event_selectjButtonActionPerformed

    private void modifyjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyjButtonActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null,"Please select a row!", "get Request",JOptionPane.ERROR_MESSAGE);
        } 
        String name = jTable1.getValueAt(row,0).toString();
        UserAccount del = system.getUseraccountdirectory().findUser(name);
        
        del.setUsername(usernamejTextField.getText());
        del.setPassword(passwordjTextField.getText());     
    }//GEN-LAST:event_modifyjButtonActionPerformed

    private void deletejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletejButtonActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null,"Please select a row!", "get Request",JOptionPane.ERROR_MESSAGE);
        } 
        String name = jTable1.getValueAt(row,0).toString();
        UserAccount del = system.getUseraccountdirectory().findUser(name);
        system.getUseraccountdirectory().deleteUserAccount(del);
        
         DeliveryManDirectory worklist= system.getDeliveryManDirectory();
         DeliveryMan man = worklist.findDeliveryMan(name);
         worklist.getDeliveryManDirectory().remove(man);
        
    }//GEN-LAST:event_deletejButtonActionPerformed

    private void createjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createjButtonActionPerformed
        // TODO add your handling code here:
        String name = createusernamejTextField1.getText();
        String password= createpasswordjTextField1.getText();
//        UserAccount man = system.getUseraccountdirectory().createUserAccount(name, password, new DeliverManRole());
        system.getDeliveryManDirectory().addDeliveryMan(new DeliveryMan(name));
    }//GEN-LAST:event_createjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton createjButton;
    private javax.swing.JTextField createpasswordjTextField1;
    private javax.swing.JTextField createusernamejTextField1;
    private javax.swing.JButton deletejButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modifyjButton;
    private javax.swing.JTextField passwordjTextField;
    private javax.swing.JButton selectjButton;
    private javax.swing.JTextField usernamejTextField;
    // End of variables declaration//GEN-END:variables
}
